/* This file is part of mantoQSAR.

mantoQSAR - Quantitative structure-activity relationship descriptor 
			calculation and modeling for biomolecules.
			
Copyright (C) 2016  Jörg Kittelmann


mantoQSAR is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, 
or any later version.

mantoQSAR is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with mantoQSAR. If not, see <http://www.gnu.org/licenses/>.
*/

package org.mantoQSAR.gui.molecule;

import java.awt.BorderLayout;
import javax.swing.JPanel;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//org.mantoQSAR.gui//DescriptorValue//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "DescriptorValueTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "editor", openAtStartup = true, position = 2)
@ActionID(category = "Window", id = "org.mantoQSAR.gui.DescriptorValueTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_DescriptorValueAction",
        preferredID = "DescriptorValueTopComponent"
)
@Messages({
    "CTL_DescriptorValueAction=DescriptorValue",
    "CTL_DescriptorValueTopComponent=Descriptor Values",
    "HINT_DescriptorValueTopComponent=See calculated descriptor values here."
})
public final class DescriptorValueTopComponent extends TopComponent {

    public DescriptorValueTopComponent() {
        initComponents();
        initMyComponents();
        setName(Bundle.CTL_DescriptorValueTopComponent());
        setToolTipText(Bundle.HINT_DescriptorValueTopComponent());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    private void initMyComponents() {
        
    //JPanel mainpanel = new JPanel();
    
    this.setLayout(new BorderLayout());
    
    JPanel centerPanel = new JPanel();
    centerPanel.setLayout(new BorderLayout());
    
    JPanel headerPaneTop = new DescriptorTableHeaderPanel();
    DescriptorTablePanel tablePanel = new DescriptorTablePanel();

    centerPanel.add(headerPaneTop, BorderLayout.PAGE_START);
    centerPanel.add(tablePanel, BorderLayout.CENTER);
    
    this.add(centerPanel, BorderLayout.CENTER);
    }
}
